name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3.4

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: make check
