name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        erlang_version:
        - "23"
        - "24"

    container:
      image: erlang:${{ matrix.erlang_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: make check
